api_platform:
  metadata_backward_compatibility_layer: false
  defaults:
    normalization_context:
      skip_null_values: true
  mapping:
    paths:
      - '%kernel.project_dir%/src/DTO'
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [ 3 ]
  formats:
    jsonld: [ 'application/ld+json' ]
