fos_js_routing:
  routes_to_expose: [
    'ajax_fetch_entry',
    'ajax_fetch_entry_comment',
    'ajax_fetch_post',
    'ajax_fetch_post_comment',
    'ajax_fetch_post_comments',
    'ajax_fetch_user_popup',
    'ajax_fetch_title',
    'ajax_fetch_embed',
    'ajax_fetch_duplicates',

    'theme_settings'
  ]
