framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    annotations: false #no longer supported
    http_method_override: false
    handle_all_throwables: true
    trusted_proxies: '%env(string:default::TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: '%env(REDIS_DNS)%'
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 1814400 # Match the remember_me lifetime
        storage_factory_id: session.storage.factory.native

    http_client:
        default_options:
            headers:
                'User-Agent': 'Mbin/1.7.1-rc5 (+https://%kbin_domain%/agent)'

    #esi: true
    #fragments: true
    php_errors:
        log: true
