knpu_oauth2_client:
  clients:
    azure:
      type: azure
      client_id: '%oauth_azure_id%'
      client_secret: '%oauth_azure_secret%'
      tenant: '%oauth_azure_tenant%'
      redirect_route: oauth_azure_verify
      redirect_params: { }
    facebook:
      type: facebook
      client_id: '%oauth_facebook_id%'
      client_secret: '%oauth_facebook_secret%'
      redirect_route: oauth_facebook_verify
      redirect_params: { }
      graph_api_version: v2.12
    google:
      type: google
      client_id: '%oauth_google_id%'
      client_secret: '%oauth_google_secret%'
      redirect_route: oauth_google_verify
      redirect_params: { }
    github:
      type: github
      client_id: '%oauth_github_id%'
      client_secret: '%oauth_github_secret%'
      redirect_route: oauth_github_verify
      redirect_params: { }
    privacyportal:
      type: generic
      provider_class: League\OAuth2\Client\Provider\PrivacyPortal
      client_id: '%oauth_privacyportal_id%'
      client_secret: '%oauth_privacyportal_secret%'
      redirect_route: oauth_privacyportal_verify
      redirect_params: { }
    keycloak:
      type: keycloak
      client_id: '%oauth_keycloak_id%'
      client_secret: '%oauth_keycloak_secret%'
      auth_server_url: '%oauth_keycloak_uri%'
      realm: '%oauth_keycloak_realm%'
      version: '%oauth_keycloak_version%'
      redirect_route: oauth_keycloak_verify
      redirect_params: { }
    simplelogin:
      type: generic
      client_id: '%oauth_simplelogin_id%'
      client_secret: '%oauth_simplelogin_secret%'
      redirect_route: oauth_simplelogin_verify
      redirect_params: { }
      provider_class: 'App\Provider\SimpleLogin'
    zitadel:
      type: generic
      client_id: '%oauth_zitadel_id%'
      client_secret: '%oauth_zitadel_secret%'
      provider_options:
          base_url: '%oauth_zitadel_base_url%'
      redirect_route: oauth_zitadel_verify
      redirect_params: { }
      provider_class: 'App\Provider\Zitadel'
    authentik:
      type: generic
      client_id: '%oauth_authentik_id%'
      client_secret: '%oauth_authentik_secret%'
      provider_options:
          base_url: '%oauth_authentik_base_url%'
      redirect_route: oauth_authentik_verify
      redirect_params: { }
      provider_class: 'App\Provider\Authentik'