framework:
<<<<<<< ours
  default_locale: "%env(KBIN_DEFAULT_LANG)%"
  translator:
    default_path: "%kernel.project_dir%/translations"
    fallbacks:
      - en
#    providers:
#      crowdin:
#        dsn: "%env(CROWDIN_DSN)%"
#      loco:
#        dsn: "%env(LOCO_DSN)%"
#      lokalise:
#        dsn: "%env(LOKALISE_DSN)%"
#      phrase:
#        dsn: "%env(PHRASE_DSN)%"
=======
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
>>>>>>> theirs
