twig:
    globals:
        mercure_public_url: "%env(MERCURE_PUBLIC_URL)%"

    default_path: "%kernel.project_dir%/templates"
    form_themes:
        [
            "form_div_layout.html.twig",
            "@MeteoConceptHCaptcha/hcaptcha_form.html.twig",
        ]
