twig:
    globals:
        mercure_public_url: '%env(MERCURE_PUBLIC_URL)%'

    file_name_pattern: '*.twig'
    form_themes:
        [
            'form_div_layout.html.twig',
            '@MeteoConceptHCaptcha/hcaptcha_form.html.twig',
        ]

when@test:
    twig:
        strict_variables: true
