services:
  www:
    # Builds the Docker image from scratch
    build:
      dockerfile: docker/caddy/Dockerfile
      target: dev
    container_name: mbin-www
    restart: unless-stopped
    networks:
      - mbin_external_network
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2019/metrics || exit 1"]
    ports:
      - 8008:80
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./:/var/www/mbin
    environment:
      - SERVER_NAME=:80 # the address that the web server binds
      - PHP_FASTCGI_HOST=php:9000 # caddy forward traffic to this host via fastcgi
      - MERCURE_PUBLISHER_JWT_KEY=$MERCURE_JWT_SECRET
      - MERCURE_SUBSCRIBER_JWT_KEY=$MERCURE_JWT_SECRET
    depends_on:
      - php

  php:
    # Builds the Docker image from scratch
    build:
      dockerfile: docker/php/Dockerfile
      target: dev
    container_name: mbin-php
    command: php-fpm
    working_dir: /var/www/mbin
    restart: unless-stopped
    networks:
      - mbin_external_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "REQUEST_METHOD=GET SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping cgi-fcgi -bind -connect localhost:9000 || exit 1",
        ]
    volumes:
      - ./docker/php/entrypoint.sh:/entrypoint.sh
      - ./:/var/www/mbin/
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini
      - ./docker/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    # If you want to change configs locally, without rebuilding the image use:
    #  - ../docker/config:/var/www/mbin/config
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  node:
    image: "node:22.5.1-alpine3.20"
    command: docker/node/build.sh
    container_name: node-builder
    entrypoint:
      - sh
      - "-c"
    working_dir: /var/www/mbin
    depends_on:
      php:
        condition: service_healthy
    networks:
      - mbin_external_network
    volumes:
      - ./:/var/www/mbin/

  messenger:
    # Builds the Docker image from scratch
    build:
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    networks:
      - mbin_external_network
    command: bin/console -vvvv messenger:consume --all --time-limit=3600
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'messenger[:]consume' || exit 1"]
    volumes:
      - ./:/var/www/mbin/
    # If you want to change configs locally, without rebuilding the image use:
    #  - ../docker/config:/var/www/mbin/config
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  redis:
    image: redis:alpine
    container_name: mbin-redis
    restart: unless-stopped
    networks:
      - mbin_external_network
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    volumes:
      - redis:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  db:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    container_name: mbin-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - mbin_external_network
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: mbin-rabbitmq
    restart: unless-stopped
    networks:
      - mbin_external_network
    env_file:
      - .env
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672

  # Add your favorite reverse proxy (e.g nginx) which accept incoming HTTPS
  # traffic and forward to http://www:80
  #nginx:
  #  image: nginx
  #  container_name: mbin-nginx
  #  networks:
  #    - mbin_external_network
  #  ports:
  #    - 443:443
  #  volumes:
  #    - ./docker/nginx.conf:/etc/nginx/nginx.conf

  # Example of a SMTP docker service
  # More info: https://hub.docker.com/r/ixdotai/smtp
  #mailserver:
  #  image: ixdotai/smtp:latest
  #  networks:
  #    - mbin_external_network
  #  environment:
  #    - SMARTHOST_ADDRESS=mail.mysmtp.com
  #    - SMARTHOST_PORT=587
  #    - SMARTHOST_USER=myuser
  #    - SMARTHOST_PASSWORD=secret
  #    - SMARTHOST_ALIASES=*.mysmtp.com

networks:
  mbin_external_network:

volumes:
  caddy_config:
  caddy_data:
  logs:
  postgres:
  rabbitmq:
  redis:
