# Production environment override
services:
    php:
        build:
            dockerfile: docker/Dockerfile
            context: .
            target: prod

    messenger:
        build:
            dockerfile: docker/Dockerfile
            context: .
            target: prod
