# Production environment override
services:
    php:
        build:
            dockerfile: docker/Dockerfile
            context: .
            target: prod
        environment:
            APP_ENV: prod

    messenger:
        build:
            dockerfile: docker/Dockerfile
            context: .
            target: prod
        environment:
            APP_ENV: prod
        deploy:
            mode: replicated
            replicas: 6
