version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch"]
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
#  MailHog is an email testing tool useful during development
#  All sent emails will be available in its web UI at http://localhost:8025/
#  After uncommenting lines below set MAILER_DSN=smtp://mailhog:1025 in .env file
#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - 1025:1025
#      - 8025:8025

  nodejs:
    image: node:18-alpine
    command: sh -c "yarn && yarn watch"
    volumes:
      - ./:/srv/app
    working_dir: "/srv/app"

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
