version: "3.9"

services:
  www:
    environment:
      - MERCURE_JWT_SECRET=!ChangeThisMercureHubJWTSecretKey!

  redis:
    environment:
      - REDIS_PASSWORD=!ChangeThisRedisPass!

  db:
    environment:
      - POSTGRES_PASSWORD=!ChangeThisPostgresPass!

  rabbitmq:
    environment:
      - RABBITMQ_PASSWORD=!ChangeThisRabbitPass!
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

