version: "3.9"

services:
  www:
    environment:
      - MERCURE_JWT_SECRET=!ChangeThisMercureHubJWTSecretKey!

  redis:
    environment:
      - REDIS_PASSWORD=!ChangeThisRedisPass!

  db:
    environment:
      - POSTGRES_PASSWORD=!ChangeThisPostgresPass!

  rabbitmq:
    environment:
      - RABBITMQ_PASSWORD=!ChangeThisRabbitPass!
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  # Set the following HTTPS variables to TRUE if your environment is using a 
  # valid certificate behind a reverse proxy. This is likely true for most
  # production environments and is required for proper federation, that is, this
  # will ensure the webfinger responses include `https:` in the URLs generated.

  php:
    environment:
      - HTTPS=TRUE

  messenger:
    environment:
      - HTTPS=TRUE

  messenger_ap:
    environment:
      - HTTPS=TRUE
