#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

if [ "$1" == "php-fpm" ] || [ "$1" == "php" ] || [ "$1" == "bin/console" ]; then
    # if running as a service install assets
    if [ "$1" == "php-fpm" ]; then
        echo "Starting as servce..."

        # In production: dump the production PHP config files,
        # validate the installed packages (no dev) and dump prod config
        if [ "$APP_ENV" == "prod" ]; then
            cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
            cp "$PHP_INI_DIR/conf.d/app.ini-production" "$PHP_INI_DIR/conf.d/app.prod.or.dev.ini"
            composer install --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress
            composer dump-env prod
        fi

        # In development: dump the development PHP config files,
        # validate the installed packages (including dev dependencies) and dump dev config
        if [ "$APP_ENV" == "dev" ]; then
            cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
            cp "$PHP_INI_DIR/conf.d/app.ini-development" "$PHP_INI_DIR/conf.d/app.prod.or.dev.ini"
            composer install --prefer-dist --no-scripts --no-progress
            composer dump-env dev
        fi
    fi

    echo "Waiting for db to be ready..." 
    ATTEMPTS_LEFT_TO_REACH_DATABASE=60
    until [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ] || DATABASE_ERROR=$(bin/console dbal:run-sql "SELECT 1" 2>&1); do
        if [ $? -eq 255 ]; then
            # If the Doctrine command exits with 255, an unrecoverable error occurred
            ATTEMPTS_LEFT_TO_REACH_DATABASE=0
            break
        fi
        sleep 1
        ATTEMPTS_LEFT_TO_REACH_DATABASE=$((ATTEMPTS_LEFT_TO_REACH_DATABASE - 1))
        echo "Still waiting for db to be ready... Or maybe the db is not reachable. $ATTEMPTS_LEFT_TO_REACH_DATABASE attempts left"
    done

    if [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ]; then
        echo "The database is not up or not reachable:"
        echo "$DATABASE_ERROR"
        exit 1
    else
        echo "The db is now ready and reachable"
    fi

    if [ "$( find ./migrations -iname '*.php' -print -quit )" ]; then
        bin/console doctrine:migrations:migrate --no-interaction
    fi

    if [ -n "$ENABLE_ACL" ]; then
        if [ "$ENABLE_ACL" -eq 1 ]; then
            setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var
            setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var
        else
            echo "Filesystem ACL is disabled."
        fi
    else
        echo "ENABLE_ACL is not set!"
    fi
fi

exec "$@"
