api_combined_cursor:
    controller: App\Controller\Api\Combined\CombinedRetrieveApi::cursorCollection
    path: /api/combined/2.0
    methods: [ GET ]
    format: json

api_combined_user_cursor:
    controller: App\Controller\Api\Combined\CombinedRetrieveApi::cursorUserCollection
    path: /api/combined/2.0/{collectionType}
    requirements:
        collectionType: subscribed|moderated|favourited
    methods: [ GET ]
    format: json

api_combined:
  controller: App\Controller\Api\Combined\CombinedRetrieveApi::collection
  path: /api/combined
  methods: [ GET ]
  format: json

api_combined_user:
  controller: App\Controller\Api\Combined\CombinedRetrieveApi::userCollection
  path: /api/combined/{collectionType}
  requirements:
    collectionType: subscribed|moderated|favourited
  methods: [ GET ]
  format: json
