tag_overview:
  controller: App\Controller\Tag\TagOverviewController
  path: /tag/{name}
  methods: [GET]

tag_entries:
  controller: App\Controller\Tag\TagEntryFrontController
  defaults: { sortBy: hot, time: ~ }
  path: tag/{name}/threads/{sortBy}/{time}
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

tag_comments:
  controller: App\Controller\Tag\TagCommentFrontController
  defaults: { sortBy: hot, time: ~ }
  path: tag/{name}/comments/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

tag_posts:
  controller: App\Controller\Tag\TagPostFrontController
  defaults: { sortBy: hot, time: ~ }
  path: tag/{name}/posts/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

tag_people:
  controller: App\Controller\Tag\TagPeopleFrontController
  defaults: { sortBy: hot, time: ~ }
  path: tag/{name}/people
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

tag_ban:
  path: /tag/{name}/ban
  methods: [POST]
  controller: App\Controller\Tag\TagBanController::ban

tag_unban:
  path: /tag/{name}/unban
  methods: [POST]
  controller: App\Controller\Tag\TagBanController::unban

tag_block:
  controller: App\Controller\Tag\TagBlockController::block
  path: /tag/{name}/block
  methods: [ POST ]

tag_unblock:
  controller: App\Controller\Tag\TagBlockController::unblock
  path: /tag/{name}/unblock
  methods: [ POST ]

tag_subscribe:
  controller: App\Controller\Tag\TagSubscriptionController::subscribe
  path: /tag/{name}/subscribe
  methods: [ POST ]

tag_unsubscribe:
  controller: App\Controller\Tag\TagSubscriptionController::unsubscribe
  path: /tag/{name}/unsubscribe
  methods: [ POST ]
