api_tag_entries:
  controller: App\Controller\Api\Tag\TagContentRetrieveApi::entries
  path: /api/tag/{name}/entries
  methods: [ GET ]
  format: json

api_tag_entry_comments:
  controller: App\Controller\Api\Tag\TagContentRetrieveApi::entryComments
  path: /api/tag/{name}/entryComments
  methods: [ GET ]
  format: json

api_tag_posts:
  controller: App\Controller\Api\Tag\TagContentRetrieveApi::posts
  path: /api/tag/{name}/posts
  methods: [ GET ]
  format: json

api_tag_post_comments:
  controller: App\Controller\Api\Tag\TagContentRetrieveApi::postComments
  path: /api/tag/{name}/postComments
  methods: [ GET ]
  format: json
