api_admin_entry_purge:
  controller: App\Controller\Api\Entry\Admin\EntriesPurgeApi
  path: /api/admin/entry/{entry_id}/purge
  methods: [ DELETE ]
  format: json

api_admin_entry_change_magazine:
  controller: App\Controller\Api\Entry\Admin\EntriesChangeMagazineApi
  path: /api/admin/entry/{entry_id}/change-magazine/{target_id}
  methods: [ PUT ]
  format: json

api_admin_comment_purge:
  controller: App\Controller\Api\Entry\Comments\Admin\EntryCommentsPurgeApi
  path: /api/admin/comment/{comment_id}/purge
  methods: [ DELETE ]
  format: json

api_admin_post_purge:
  controller: App\Controller\Api\Post\Admin\PostsPurgeApi
  path: /api/admin/post/{post_id}/purge
  methods: [ DELETE ]
  format: json

api_admin_post_comment_purge:
  controller: App\Controller\Api\Post\Comments\Admin\PostCommentsPurgeApi
  path: /api/admin/post-comment/{comment_id}/purge
  methods: [ DELETE ]
  format: json

api_admin_user_retrieve_banned:
  controller: App\Controller\Api\User\Admin\UserRetrieveBannedApi::collection
  path: /api/admin/users/banned
  methods: [ GET ]
  format: json

api_admin_user_ban:
  controller: App\Controller\Api\User\Admin\UserBanApi::ban
  path: /api/admin/users/{user_id}/ban
  methods: [ POST ]
  format: json

api_admin_user_unban:
  controller: App\Controller\Api\User\Admin\UserBanApi::unban
  path: /api/admin/users/{user_id}/unban
  methods: [ POST ]
  format: json

api_admin_user_delete_account:
  controller: App\Controller\Api\User\Admin\UserDeleteApi
  path: /api/admin/users/{user_id}/delete_account
  methods: [ DELETE ]
  format: json

api_admin_user_purge:
  controller: App\Controller\Api\User\Admin\UserPurgeApi
  path: /api/admin/users/{user_id}/purge_account
  methods: [ DELETE ]
  format: json

api_admin_user_verify:
  controller: App\Controller\Api\User\Admin\UserVerifyApi
  path: /api/admin/users/{user_id}/verify
  methods: [ PUT ]
  format: json

api_admin_retrieve_settings:
  controller: App\Controller\Api\Instance\Admin\InstanceRetrieveSettingsApi
  path: /api/instance/settings
  methods: [ GET ]
  format: json

api_admin_update_settings:
  controller: App\Controller\Api\Instance\Admin\InstanceUpdateSettingsApi
  path: /api/instance/settings
  methods: [ PUT ]
  format: json

api_admin_update_pages:
  controller: App\Controller\Api\Instance\Admin\InstanceUpdatePagesApi
  path: /api/instance/{page}
  methods: [ PUT ]
  format: json

api_admin_retrieve_client_stats:
  controller: App\Controller\Api\OAuth2\Admin\RetrieveClientStatsApi
  path: /api/clients/stats
  methods: [ GET ]
  format: json

api_admin_retrieve_client:
  controller: App\Controller\Api\OAuth2\Admin\RetrieveClientApi
  path: /api/clients/{client_identifier}
  methods: [ GET ]
  format: json

api_admin_retrieve_client_collection:
  controller: App\Controller\Api\OAuth2\Admin\RetrieveClientApi::collection
  path: /api/clients
  methods: [ GET ]
  format: json

api_admin_update_defederated_instances:
  controller: App\Controller\Api\Instance\Admin\InstanceUpdateFederationApi
  path: /api/defederated
  methods: [ PUT ]
  format: json

api_admin_purge_magazine:
  controller: App\Controller\Api\Magazine\Admin\MagazinePurgeApi
  path: /api/admin/magazine/{magazine_id}/purge
  methods: [ DELETE ]
  format: json
