admin_users:
  controller: App\Controller\Admin\AdminUserController
  defaults: { withFederated: false }
  path: /admin/users/{withFederated}
  methods: [ GET ]

admin_settings:
  controller: App\Controller\Admin\AdminSettingsController
  path: /admin/settings
  methods: [ GET, POST ]

admin_federation:
  controller: App\Controller\Admin\AdminFederationController
  path: /admin/federation
  methods: [ GET, POST ]

admin_pages:
  controller: App\Controller\Admin\AdminPagesController
  path: /admin/pages/{page}
  methods: [ GET, POST ]

admin_cc:
  controller: App\Controller\Admin\AdminClearCacheController
  path: /admin/cc
  methods: [ GET ]

admin_dashboard:
  controller: App\Controller\Admin\AdminDashboardController
  path: /admin/{statsPeriod}/{withFederated}
  defaults: { statsType: content, statsPeriod: -1, withFederated: false }
  methods: [ GET ]
