front:
  controller: App\Controller\Entry\EntryFrontController::front
  defaults: { subscription: home, sortBy: hot, time: '∞', type: all, federation: all, content: threads }
  path: /{subscription}/{sortBy}/{time}/{type}/{federation}/{content}
  methods: [GET]
  requirements:
    subscription: "%default_subscription_options%"
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"
    type: "%default_type_options%"
    federation: "%default_federation_options%"
    content: "%default_content_options%"

front_redirect:
  controller: App\Controller\Entry\EntryFrontController::front_redirect
  defaults: { sortBy: hot, time: '∞', type: all, federation: all, content: threads }
  path: /{sortBy}/{time}/{type}/{federation}/{content}
  methods: [GET]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"
    type: "%default_type_options%"
    federation: "%default_federation_options%"
    content: "%default_content_options%"

front_magazine:
  controller: App\Controller\Entry\EntryFrontController::magazine
  defaults: { sortBy: hot, time: '∞', type: all, federation: all, content: threads }
  path: /m/{name}/{sortBy}/{time}/{type}/{federation}/{content}
  methods: [GET]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"
    type: "%default_type_options%"
    federation: "%default_federation_options%"
    content: "%default_content_options%"

# Microblog compatibility stuff, redirects from the old routes' URLs

posts_front:
  controller: App\Controller\Entry\EntryFrontController::front_redirect
  defaults: { sortBy: hot, time: '∞', type: all, federation: all, content: microblog }
  path: /microblog/{sortBy}/{time}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"

posts_subscribed:
  controller: App\Controller\Entry\EntryFrontController::front_redirect
  defaults: { sortBy: hot, time: '∞', type: all, federation: all, content: microblog, subscription: 'sub' }
  path: /sub/microblog/{sortBy}/{time}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"

posts_moderated:
  controller: App\Controller\Entry\EntryFrontController::front_redirect
  defaults: { sortBy: hot, time: '∞', type: all, federation: all, content: microblog, subscription: 'mod' }
  path: /mod/microblog/{sortBy}/{time}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"

posts_favourite:
  controller: App\Controller\Entry\EntryFrontController::front_redirect
  defaults: { sortBy: hot, time: '∞', type: all, federation: all, content: microblog, subscription: 'fav' }
  path: /fav/microblog/{sortBy}/{time}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"

magazine_posts:
  controller: App\Controller\Entry\EntryFrontController::front_redirect
  defaults: { sortBy: hot, time: '∞', type: all, federation: all, content: microblog }
  path: /m/{name}/microblog/{sortBy}/{time}/{type}/{federation}
  methods: [ GET ]
  requirements:
    sortBy: "%default_sort_options%"
    time: "%default_time_options%"
    type: "%default_type_options%"
    federation: "%default_federation_options%"
