root: &root
  controller: App\Controller\Entry\EntryFrontController::root
  defaults: { sortBy: hot, time: '∞', type: ~ }
  path: /{sortBy}/{time}/{type}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

front:
  <<: *root
  controller: App\Controller\Entry\EntryFrontController::front
  defaults: { filter: all, sortBy: hot, time: '∞', type: ~ }
  path: /{filter}/{sortBy}/{time}/{type}
  methods: [GET]
  requirements:
    filter: 'sub|fav|mod|all'
    sortBy: "%front_sort_options%"

front_magazine:
  <<: *root
  controller: App\Controller\Entry\EntryFrontController::magazine
  path: /m/{name}/{sortBy}/{time}/{type}


