magazine_create:
  controller: App\Controller\Magazine\MagazineCreateController
  path: /newMagazine
  methods: [ GET, POST ]

magazine_delete:
  controller: App\Controller\Magazine\MagazineDeleteController::delete
  path: /m/{name}/delete
  methods: [ POST ]

magazine_purge:
  controller: App\Controller\Magazine\MagazineDeleteController::purge
  path: /m/{name}/purge
  methods: [ POST ]

magazine_list_all:
  controller: App\Controller\Magazine\MagazineListController
  defaults: { sortBy: hot, view: table }
  path: /magazines/{sortBy}/{view}
  methods: [ GET ]

magazine_moderators:
  controller: App\Controller\Magazine\MagazineModController
  path: /m/{name}/moderators
  methods: [ GET ]

magazine_modlog:
  controller: App\Controller\Magazine\MagazineLogController
  path: /m/{name}/modlog
  methods: [ GET ]

magazine_people:
  controller: App\Controller\Magazine\MagazinePeopleFrontController
  path: /m/{name}/people
  methods: [ GET ]

magazine_subscribe:
  controller: App\Controller\Magazine\MagazineSubController::subscribe
  path: /m/{name}/subscribe
  methods: [ POST ]

magazine_unsubscribe:
  controller: App\Controller\Magazine\MagazineSubController::unsubscribe
  path: /m/{name}/unsubscribe
  methods: [ POST ]

magazine_block:
  controller: App\Controller\Magazine\MagazineBlockController::block
  path: /m/{name}/block
  methods: [ POST ]

magazine_unblock:
  controller: App\Controller\Magazine\MagazineBlockController::unblock
  path: /m/{name}/unblock
  methods: [ POST ]
