magazine_create:
    controller: App\Controller\Magazine\MagazineCreateController
    path: /newMagazine
    methods: [GET, POST]

magazine_delete:
    controller: App\Controller\Magazine\MagazineDeleteController::delete
    path: /m/{name}/delete
    methods: [POST]

magazine_restore:
    controller: App\Controller\Magazine\MagazineDeleteController::restore
    path: /m/{name}/restore
    methods: [POST]

magazine_purge:
    controller: App\Controller\Magazine\MagazineDeleteController::purge
    path: /m/{name}/purge
    methods: [POST]

magazine_abandoned:
    controller: App\Controller\Magazine\MagazineAbandonedController
    path: /magazines/abandoned
    methods: [GET]

magazine_purge_content:
    controller: App\Controller\Magazine\MagazineDeleteController::purgeContent
    path: /m/{name}/purge_content
    methods: [POST]

magazine_list_all:
    controller: App\Controller\Magazine\MagazineListController
    defaults: { sortBy: hot, view: table }
    path: /magazines/{sortBy}/{view}
    methods: [GET]

magazine_moderators:
    controller: App\Controller\Magazine\MagazineModController
    path: /m/{name}/moderators
    methods: [GET]

magazine_modlog:
    controller: App\Controller\Magazine\MagazineLogController
    path: /m/{name}/modlog
    methods: [GET]

magazine_people:
    controller: App\Controller\Magazine\MagazinePeopleFrontController
    path: /m/{name}/people
    methods: [GET]

magazine_subscribe:
    controller: App\Controller\Magazine\MagazineSubController::subscribe
    path: /m/{name}/subscribe
    methods: [POST]

magazine_unsubscribe:
    controller: App\Controller\Magazine\MagazineSubController::unsubscribe
    path: /m/{name}/unsubscribe
    methods: [POST]

magazine_block:
    controller: App\Controller\Magazine\MagazineBlockController::block
    path: /m/{name}/block
    methods: [POST]

magazine_unblock:
    controller: App\Controller\Magazine\MagazineBlockController::unblock
    path: /m/{name}/unblock
    methods: [POST]

magazine_remove_subscriptions:
    controller: App\Controller\Magazine\MagazineRemoveSubscriptionsController
    path: /m/{name}/remove_subscriptions
    methods: [POST]

magazine_moderator_request:
    controller: App\Controller\Magazine\MagazineModeratorRequestController
    path: /m/{name}/moderator_request
    methods: [POST]

magazine_ownership_request:
    controller: App\Controller\Magazine\MagazineOwnershipRequestController::toggle
    path: /m/{name}/ownership_request
    methods: [POST]
